# Generated by Django 4.0.6 on 2022-08-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('email',),
            },
        ),
    ]
